# Generated by Django 5.2 on 2025-04-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='pessoas',
            field=models.ManyToManyField(null=True, to='diario.pessoa'),
        ),
    ]
